### ISSUE TITLE
Missing implementations of common traits such as `Eq`, `PartialEq`, `Copy`, and `Clone`

### ISSUE THREAD

**Issue by rinde** [vivax3794/error_mancer#1]
Hello, I really like your crate. It looks like a great way to improve error handling. 

I've reviewed your crate with some colleagues and we are considering to use it. We would like to know a bit more about your plans with it, are you interested in building it out to something production ready? What kind of license are you planning to use? We would potentially be interested in contributing if you are open to that. Let me know if you'd prefer to have this conversation here or somewhere else.

One thing that blocks us from using it is to be able to use it in tests for which we need `Eq` and `PartialEq` implementations of the generated error enums. Additionally, `Copy`, and `Clone` would be nice to have as well.

**Comment by vivax3794** [comment]
Right ofc! idk how those totally slipped my mind (I guess debugging macros does that to somebody), currently both crates are under MIT (as denoted in their `Cargo.toml`s), but I suppose I should add a repo wide license file. 

If people want to use it I am more than happy to continue developing the project, and also accept contributions.

**Comment by vivax3794** [comment]
Since deriving those traits by default would make it impossible to use the macro with errors that dont implement them, I have added support for annotating the function with `#[derive(...)]` to derive traits on the error enum. which will be pushed in v0.4.1
